//
//  ListItemsInteractor.swift
//  GoldenSwap
//
//  Created by Ehsan on 19/11/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListItemsBusinessLogic {
    //func doSomething(request: ListItems.Something.Request)
}

protocol ListItemsDataStore {
    //var name: String { get set }
}

class ListItemsInteractor: ListItemsBusinessLogic, ListItemsDataStore {
    var presenter: ListItemsPresentable?
    //var worker: ListItemsWorker?
    //var name: String = ""
    
    init(presenter: ListItemsPresentable) {
        self.presenter = presenter
    }
    
    
    // MARK: Do something
    
//    func doSomething(request: ListItemsModels.Request) {
//        worker = ListItemsWorker()
//        worker?.doSomeWork()
//        
//        let response = ListItemsModels.Response()
//        presenter?.presentSomething(response: response)
//    }
}
