//
//  ListItemsRouter.swift
//  GoldenSwap
//
//  Created by Ehsan on 19/11/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListItemsRoutable {
    func doSomething()
}


class ListItemsRouter: ListItemsRoutable {
    weak var viewController: ListItemsViewController?
    var dataStore: ListItemsDataStore?
    
    init(viewController: UIViewController) {
        //self.viewController = viewController
    }
    
    
    // All the routing and data passing logic will be here
    func doSomething() {
        // routing to next viewContoller
        // let vc = destinationVC

        // passing data to other contoller
        //vc.router.dataStore = input

        //viewContoller.present(vc)
    }
    
}
