//
//  ListItemsPresenter.swift
//  GoldenSwap
//
//  Created by Ehsan on 19/11/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListItemsPresentable {
    //func presentSomething(response: ListItemsModels.Response)
}

class ListItemsPresenter: ListItemsPresentable {
    weak var viewController: ListItemsDisplayable?
    
    init(viewController: ListItemsDisplayable) {
        self.viewController = viewController
    }
    
    // MARK: Do something
    
//    func presentSomething(response: ListItemsModels.Response) {
//        let viewModel = ListItemsModels.ViewModel()
//
//        viewController?.displaySomething(viewModel: viewModel)
//    }
    
    // func to display error can be added here
    
}
