//
//  RegistrationPresenter.swift
//  GoldenSwap
//
//  Created by Ehsan on 22/11/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol RegistrationPresentable {
  //func presentSomething(response: RegistrationModels.Response)
}

class RegistrationPresenter: RegistrationPresentable {
    weak var viewController: RegistrationDisplayable?
  
    init(viewController: RegistrationDisplayable) {
        self.viewController = viewController
    }
    
  // MARK: Do something
  
//  func presentSomething(response: RegistrationModels.Response) {
//    let viewModel = RegistrationModels.ViewModel()
//    
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    
  // func to display error can be added here

}
