//
//  RegistrationInteractor.swift
//  GoldenSwap
//
//  Created by Ehsan on 22/11/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol RegistrationBusinessLogic {
  //func doSomething(request: Registration.Something.Request)
}

protocol RegistrationDataStore {
  //var name: String { get set }
}

class RegistrationInteractor: RegistrationBusinessLogic, RegistrationDataStore {
  //var presenter: RegistrationPresentable?
  //var worker: RegistrationWorker?
  //var name: String = ""
  
    init(presenter: RegistrationPresentable) {
        //self.presenter = presenter
    }
    
    
  // MARK: Do something
  
//  func doSomething(request: RegistrationModels.Request) {
//    worker = RegistrationWorker()
//    worker?.doSomeWork()
//
//    let response = RegistrationModels.Response()
//    presenter?.presentSomething(response: response)
//  }
}
