//
//  RegistrationViewController.swift
//  GoldenSwap
//
//  Created by Ehsan on 22/11/2019.
//  Copyright (c) 2019 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol RegistrationDisplayable: class {
    //func displaySomething(viewModel: RegistrationModels.ViewModel)
    // func to display error can be added here
}

class RegistrationViewController: UIViewController, RegistrationDisplayable {
    //lazy var interactor: RegistrationBusinessLogic
    //lazy var router: RegistrationRoutable
    //var viewModel: RegistrationModels.ViewModel?
    
    let uiElements = RegistrationUIs()
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .green
        
        uiElements.setupViews(view: view)
        
    }
    
    
    @objc func submitAction() {
        if let phoneNumber = uiElements.phoneNumberTextField.text {
            // continue here
            // send the number to server
            // serveruse the numberr and send a sms consist of 4 digit code
        }
    }
    
    
    
//    func doSomething() {
//        let request = Registration.Something.Request()
//        interactor?.doSomething(request: request)
//    }
//
//    func displaySomething(viewModel: RegistrationModels.ViewModel) {
//        //nameTextField.text = viewModel.name
//    }
}
